const plusquamperfekt_sentenses = {
    name: "Plusquamperfekt verbs",
    desc: "Konjugation von Verben im Plusquamperfekt.",
    data: [
        { "sentence": "Ich ___ (abholen) meine Schwester vom Bahnhof.", "answer": "holte ab", "ua_infinitiv": "забирати", "ua_sentence": "Я забрав свою сестру з вокзалу.", "dict": "https://dict.com/deutsch-ukrainisch/abholen", "duden": "https://www.duden.de/rechtschreibung/abholen", "level": "A1" },
        { "sentence": "Er ___ (abholen) sein Paket von der Post.", "answer": "holte ab", "ua_infinitiv": "забирати", "ua_sentence": "Він забрав свою посилку з пошти.", "dict": "https://dict.com/deutsch-ukrainisch/abholen", "duden": "https://www.duden.de/rechtschreibung/abholen", "level": "A1" },
        { "sentence": "Wir ___ (abholen) unsere Freunde vom Flughafen.", "answer": "holten ab", "ua_infinitiv": "забирати", "ua_sentence": "Ми забрали наших друзів з аеропорту.", "dict": "https://dict.com/deutsch-ukrainisch/abholen", "duden": "https://www.duden.de/rechtschreibung/abholen", "level": "A1" },
        { "sentence": "Sie ___ (abholen) ihre Mutter vom Arzttermin.", "answer": "holte ab", "ua_infinitiv": "забирати", "ua_sentence": "Вона забрала свою маму з прийому у лікаря.", "dict": "https://dict.com/deutsch-ukrainisch/abholen", "duden": "https://www.duden.de/rechtschreibung/abholen", "level": "A2" },
        { "sentence": "Ihr ___ (abholen) die Kinder nach der Schule.", "answer": "holtet ab", "ua_infinitiv": "забирати", "ua_sentence": "Ви забрали дітей після школи.", "dict": "https://dict.com/deutsch-ukrainisch/abholen", "duden": "https://www.duden.de/rechtschreibung/abholen", "level": "A2" },
        { "sentence": "Der Busfahrer ___ (abholen) die Fahrgäste pünktlich.", "answer": "holte ab", "ua_infinitiv": "забирати", "ua_sentence": "Водій автобуса забрав пасажирів вчасно.", "dict": "https://dict.com/deutsch-ukrainisch/abholen", "duden": "https://www.duden.de/rechtschreibung/abholen", "level": "A2" },
        { "sentence": "Das Unternehmen ___ (abholen) wichtige Gäste am Bahnhof.", "answer": "holte ab", "ua_infinitiv": "забирати", "ua_sentence": "Компанія забрала важливих гостей з вокзалу.", "dict": "https://dict.com/deutsch-ukrainisch/abholen", "duden": "https://www.duden.de/rechtschreibung/abholen", "level": "B1" },
        { "sentence": "Die Delegation ___ (abholen) die Experten vom Flughafen.", "answer": "holte ab", "ua_infinitiv": "забирати", "ua_sentence": "Делегація забрала експертів з аеропорту.", "dict": "https://dict.com/deutsch-ukrainisch/abholen", "duden": "https://www.duden.de/rechtschreibung/abholen", "level": "B1" },
        { "sentence": "Wir ___ (abholen) die Waren direkt vom Lager.", "answer": "holten ab", "ua_infinitiv": "забирати", "ua_sentence": "Ми забрали товари прямо зі складу.", "dict": "https://dict.com/deutsch-ukrainisch/abholen", "duden": "https://www.duden.de/rechtschreibung/abholen", "level": "B1" },
        { "sentence": "Die Firma ___ (abholen) die defekten Produkte zur Reparatur.", "answer": "holte ab", "ua_infinitiv": "забирати", "ua_sentence": "Компанія забрала несправні продукти для ремонту.", "dict": "https://dict.com/deutsch-ukrainisch/abholen", "duden": "https://www.duden.de/rechtschreibung/abholen", "level": "B2" },
        { "sentence": "Die Logistikabteilung ___ (abholen) die Lieferung vom Hafen.", "answer": "holte ab", "ua_infinitiv": "забирати", "ua_sentence": "Логістичний відділ забрав доставку з порту.", "dict": "https://dict.com/deutsch-ukrainisch/abholen", "duden": "https://www.duden.de/rechtschreibung/abholen", "level": "B2" },
        { "sentence": "Der Kurier ___ (abholen) das Paket vom Hauptsitz der Firma.", "answer": "holte ab", "ua_infinitiv": "забирати", "ua_sentence": "Кур'єр забрав посилку з головного офісу компанії.", "dict": "https://dict.com/deutsch-ukrainisch/abholen", "duden": "https://www.duden.de/rechtschreibung/abholen", "level": "B2" }
    
    ]
};